baseURL = 'https://konstantintomashevich.github.io/'
languageCode = 'en-us'
title = 'Konstantin Tomashevich'
theme = 'hugo-theme-relearn'

languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20

[params]
  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  [[params.themeVariant]]
    identifier = 'zen-dark'

  [[params.themeVariant]]
    identifier = 'zen-light'
  
[menu]
  [[menu.shortcuts]]
      name = "<i class='fa-fw fab fa-github'></i> GitHub"
      url = "https://github.com/KonstantinTomashevich"
      weight = 1
  [[menu.shortcuts]]
      name = "<i class='fa-fw fab fa-telegram'></i> Telegram"
      url = "https://t.me/KonstantinTomashevich"
      weight = 2
  [[menu.shortcuts]]
      name = "<i class='fa-fw fab fa-linkedin'></i> LinkedIn"
      url = "https://www.linkedin.com/in/konstantin-tomashevich-1881aa152"
      weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
