name: build_and_deploy
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "github_pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3

      - name: Build
        working-directory: ${{github.workspace}}
        run: hugo

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public"

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
