name: build_and_deploy
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "github_pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Hugo
        run: |
            sudo apt-get update
            sudo apt-get install hugo

      - name: Build
        run: hugo

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public"

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
